__all__ = [
    "ping",
    "word",
    "wordguess",
    "register",
    "login",
    "avatar",
    "profile",
    "history",
    "creategame",
    "historyDebug",
    "send_try",
    "classement",
    "currentGame",
    "motValideDebug",
    "motValide",
]